# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_collector_pb2 as order__collector__pb2


class OrderCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Collect = channel.unary_stream(
                '/OrderCollector/Collect',
                request_serializer=order__collector__pb2.FirstRequest.SerializeToString,
                response_deserializer=order__collector__pb2.Order.FromString,
                )


class OrderCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Collect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Collect': grpc.unary_stream_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=order__collector__pb2.FirstRequest.FromString,
                    response_serializer=order__collector__pb2.Order.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/OrderCollector/Collect',
            order__collector__pb2.FirstRequest.SerializeToString,
            order__collector__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
