# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproduct_recommendations.proto\"N\n\x08RRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1b\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\t.Category\x12\x14\n\x0cresult_limit\x18\x03 \x01(\x05\".\n\x02\x41\x64\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"\x16\n\x03\x41\x64s\x12\x0f\n\x02\x61\x64\x18\x01 \x03(\x0b\x32\x03.Ad**\n\x08\x43\x61tegory\x12\x08\n\x04MELK\x10\x00\x12\x07\n\x03\x43\x41R\x10\x01\x12\x0b\n\x07\x44IGITAL\x10\x02\x32/\n\x0fRecommendations\x12\x1c\n\tRecommend\x12\t.RRequest\x1a\x04.Adsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'product_recommendations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CATEGORY._serialized_start = 185
    _CATEGORY._serialized_end = 227
    _RREQUEST._serialized_start = 33
    _RREQUEST._serialized_end = 111
    _AD._serialized_start = 113
    _AD._serialized_end = 159
    _ADS._serialized_start = 161
    _ADS._serialized_end = 183
    _RECOMMENDATIONS._serialized_start = 229
    _RECOMMENDATIONS._serialized_end = 276
# @@protoc_insertion_point(module_scope)
